fav_animal = input("What is your favorite animal?\n> ")
fav_reason = input("What do you like about them?\n> ")
animal_color = input("What color/s are they?\n> ")
animal_habitat = input("Where do they live?\n> ")
animal_food = input("What do they eat?\n> ")
animal_sound = input("What sound do they make?\n> ")
animal_size = input("Would you say they are a small, medium, or large animal?\n> ")
animal_type = input("Are they a mammal, reptile, amphibian, etc.?\n> ")
animal_fact = input("What is a fun fact about your animal?\n> ")
animal_texture = input("Are they furry, scaly, feathery, etc.?\n> ")
print("Your favorite animal is the " + fav_animal + " because " + fav_reason + ". They are a " + animal_type + " and they live in " + animal_habitat + ". They are " + animal_color +  " and the make a " + animal_sound + " sound. They are " + animal_size +  " and " + animal_texture + ". They eat " + animal_food + ". A fun fact about them is that " + animal_fact + ".")