q_1 = input("1.Give me a number greater than 1\n> ")
q_2 = input("2.Give me a number less than 20\n> ")
q_3 = input("3.Give me a number greater than or equal to 67\n> ")
q_4 = input("4.Give me a number equal to 4\n> ")
q_5 = input("5.Give me a number less than or equal to 80\n> ")
q_6 = input("6.Give me a number greater than 70 or less than 50\n> ")
q_7 = input("7.Give me a number less than 100 and greater than 25\n> ")
q_8 = input("8.Give me a number less than 0 or equal to 100\n> ")


print()
print("Question 1")
print(int(q_1) > 1)
print()
print("Question 2")
print(int(q_2) < 20)
print()
print("Question 3")
print(int(q_3) >= 67)
print()
print("Question 4")
print(int(q_4) == 4)
print()
print("Question 5")
print(int(q_5) <= 80)
print()
print("Question 6")
print(int(q_6) > 70 or int(q_6) < 50)
print()
print("Question 7")
print(int(q_7) < 100 and int(q_7) > 25)
print()
print("Question 8")
print(int(q_8) < 0 or int(q_8) == 100)
print()