countdown = input("How many seconds until launch?\n> ")
oxygen_tanks = input("How many oxygen tanks are there?\n> ")
food_packs = input("How many food packs are there?\n> ")
water_packs = input("How many water packs are there?\n> ")
print()
print("There are " + countdown + " seconds until launch")
print("There are " + oxygen_tanks + " oxygen tanks")
print("There are " + food_packs + " food packs")
print("There are " + water_packs + " water packs")
print()
oxygen_tanks = input("Confirm how many oxygen tanks there are. They are important.\n> ")
print()
print("There are " + countdown + " seconds until launch")
print("There are " + oxygen_tanks + " oxygen tanks")
print("There are " + food_packs + " food packs")
print("There are " + water_packs + " water packs")